### ISSUE TITLE
Добавить Camera и RRC

### ISSUE THREAD

**Issue by SapozhnikUA** [waze-ua/wme_levelreset#3]
@madnut-ua 
Добавить проверку лока Камер и ЖД переезда. 
Дефолтные значения
Camera - 4
RRC - 3 
Обязательно проверять, чтоб не было  установлено "авто". Когда L5 ставит ЖД переезд и не меняет вручную лок, Л3 не может больше ничего с ним сделать.

**Comment by madnut-ua** [comment]
Добавил поддержку камер и переездов. пока без доп. проверок на "авто", проверяй пока так

**Comment by SapozhnikUA** [comment]
Вроде все ok.
Локи меняет, отображается крАсива )))



Andrey Fomenko
Ukraine, Kyiv
***@***.***


вс, 29 мая 2022 г. в 20:16, madnut-ua ***@***.***>:
